apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: namespaceconfig-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator-01
    app.kubernetes.io/part-of: operator-01
    app.kubernetes.io/managed-by: kustomize
  name: namespaceconfig-all-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
