---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - namespaceconfig.myoperator.io
  resources:
  - namespaceconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - namespaceconfig.myoperator.io
  resources:
  - namespaceconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - namespaceconfig.myoperator.io
  resources:
  - namespaceconfigs/status
  verbs:
  - get
  - patch
  - update
